hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.showSql=true
hibernate.connection.driverClass=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/estatedb
hibernate.connection.username=postgres
hibernate.connection.password=123456
